environment:
  services:
      - orchardup/mysql
build:
  run:
    - echo meow 

plugins:
  - docker_publish:
      repository: docker-registry:80
      name: funnel/deal
      hipchat:
        - 332323
